version: '3'
services:
  spark-master: 
    image: apachehudi/hudi-hadoop_2.8.4-hive_2.3.3-sparkmaster_2.4.4
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "4040:4040"      
    environment:
      - INIT_DAEMON_STEP=setup_spark
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=2G
      - SPARK_DRIVER_MEMORY=1G
      - SPARK_EXECUTOR_MEMORY=1G
    volumes:
      - shared_data:/data      
  spark-worker-1:
    image: apachehudi/hudi-hadoop_2.8.4-hive_2.3.3-sparkworker_2.4.4
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=2G"
      - "SPARK_DRIVER_MEMORY=1G"
      - "SPARK_EXECUTOR_MEMORY=1G"
    volumes:
      - shared_data:/data
      
  spark-worker-2:
    image: apachehudi/hudi-hadoop_2.8.4-hive_2.3.3-sparkworker_2.4.4
    container_name: spark-worker-2
    depends_on:
      - spark-master
    ports:
      - "8082:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SPARK_WORKER_CORES=1"
      - "SPARK_WORKER_MEMORY=2G"
      - "SPARK_DRIVER_MEMORY=1G"
      - "SPARK_EXECUTOR_MEMORY=1G"
     volumes:
      - shared_data:/data
volumes:
    shared_data:
   
    
